### ISSUE TITLE
[Suggestion] More Interactable Objects

### ISSUE THREAD

**Issue by BrowsingTheInternet** [coderCleric/Poltergeist#4]
Full interact control toggle in the config file to interact with all objects with few reasonable limitations

Those are:

- Monitor Buttons
- Hydraulic Door Buttons
- DropShip
- Bell
- Decorations (Plushie, Pumpkin, Shower, TV, Table Candles)
- Ship Horn
- Inverse and Regular teleporter Buttons
- Circuit Box Open/Close & Flip Switches
- Open Cabinet Doors & Cabinet Doors Inside The Facility
- Valves

If you strive to a non-griefing mod, I utterly understand if you ignore this suggestion of mine.

**Comment by coderCleric** [comment]
I probably won't do something to this degree due to griefing concerns, but I do plan to add more interactable objects as time goes on.

**Comment by CoolLKKPS** [comment]
> Full interact control toggle in the config file to interact with all objects with few reasonable limitations
> Those are:
> * Inverse and Regular teleporter Buttons

if Ghost can control Regular teleporter Buttons, that's too OP, except limit teleport count

> * Valves

valve steams is design to block player sight, if Ghost can turn off, in some situation that will be useful

and that definitely must configurable and only host config will be used for everyone, and should add 1s interact cooldown by default, bc this mod can use in vanilla game, which is good in my opinion, but need more balance

**Comment by TheBlackEntity** [comment]
> Open Cabinet Doors & Cabinet Doors Inside The Facility
I think this should definitely be a thing, since you can already interact with normal doors

> Decorations (Plushie, Pumpkin, Shower, TV, Table Candles)
That would be awesome, since you can already make the horns go off

> Circuit Box Open/Close & Flip Switches
Definitely! But maybe only temporary?
I don't think it would be much fun, if a dead player permanently turned off the lights...

> Hydraulic Door Buttons
I think this should only work for closing them and only if there's at least one person inside the ship to counter griefing


I don't think the rest should be added to this mod, especially since you can use it in vanilla lobbies too...

**Comment by coderCleric** [comment]
I'm going to look into how to mitigate spamming, then look more specifically at what objects to add support for.

**Comment by coderCleric** [comment]
Added what of these I plan to in 0.3.0.
